version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vega_blog_backend:dev   # ✅ Always tag image for reuse
    container_name: vega_blog_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: yarn start

    volumes:
      - .:/app
    # network_mode: host
